use numeric USER in Dockerfiles
This makes it so that Kubernetes can determine that that USER is not
 uid 0 (root) and such that the image should be run as non-root.

Without USER set to numeric uid kubernetes users need to specify
`runAsUser: 1000` to overcome that.

This is what Kubernetes says without this commit (or the workaround):
```
Error: container has runAsNonRoot and image has non-numeric user (seleuser),
cannot verify user is non-root ...
```